### ISSUE TITLE
Browser-first implementation possible?

### ISSUE THREAD

**Issue by ikreymer** [RangerMauve/js-ipfs-fetch#1]
This is sort of a high level question about the architecture, but it looks like currently the architecture is designed to work in node first, and not the browser. I think the main benefit of `fetch()` compatibility is that it should work exactly like the browser fetch API (since Node does not have a native fetch).

Is it possible to make this implementation work exactly like the browser fetch?

**Comment by RangerMauve** [comment]
I got it working with browserify. 😅

**Comment by RangerMauve** [comment]
Should be working now in 1.3.0, feel free to reopen if there are more issues.
