### ISSUE TITLE
Cannot find module 'ipfs'

### ISSUE THREAD

**Issue by FloUz-ai** [RangerMauve/js-ipfs-fetch#14]
I seems there is some missing dependancies..  :  ```Cannot find module 'ipfs'```

It doesn not work neithe when I download the ipfs package

**Comment by RangerMauve** [comment]
Oh dang, the README hasn't been updated in a while.

It should instead look like

```JavaScript
const IPFS = require('ipfs-core')
const makeIpfsFetch = require('ipfs-fetch')

const ipfs = await IPFS.create()
const fetch = await makeIpfsFetch({ipfs})
```

I'll update it in a sec.
