### ISSUE TITLE
Can't resolve 'fs' in fetch-request-body-to-async-iterator when packaging for web

### ISSUE THREAD

**Issue by ikreymer** [RangerMauve/js-ipfs-fetch#2]
I ran into an issue with webpack packaging js-ipfs-fetch, as it was looking for `fs`.
I ended up commenting that line out, and then was able to build.. (Not sure why it was erroring on load in webpack exactly)
This is sort of related to #1, as it seems to assume that this is loaded in a node environmment.

The error I got was (perhaps this issue should be in the 'fetch-request-body-to-async-iterator' module?)

```
ERROR in ./node_modules/fetch-request-body-to-async-iterator/index.js
Module not found: Error: Can't resolve 'fs' in '.../node_modules/fetch-request-body-to-async-iterator'
 @ ./node_modules/fetch-request-body-to-async-iterator/index.js 45:15-28
 @ ./node_modules/make-fetch/index.js
 @ ./node_modules/js-ipfs-fetch/index.js
 @ ./src/blockloaders.js
 @ ./src/loaders.js
 @ ./src/sw.js
```

**Comment by RangerMauve** [comment]
Mind opening an issue on the GH page for that project? I'll update it some time early next week

**Comment by RangerMauve** [comment]
Fixed by adding a `browser` field setting `fs: false`. Out in 1.3.0
