### ISSUE TITLE
how to include in vue project

### ISSUE THREAD

**Issue by travelixEarth** [RangerMauve/js-ipfs-fetch#7]
is it possible to use this in a vue project? if so, could you provide a quick example of how to do so? 🙏

i'm pulling my hair out trying to build a simple app that interacts directly with ipfs instead of going using the opensea api... this project is a much needed bridge!

thank you! 💚🌎

**Comment by RangerMauve** [comment]
Sadly, I don't have experience using IPFS with Vue. Are you able to `npm install ipfs-fetch` and then `import` it in your app code?
